# Generated by Django 5.0.3 on 2024-07-02 12:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='container', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(blank=True, default='2021-01-01 12:00:00', max_length=50, null=True)),
                ('session_duration', models.IntegerField(blank=True, default=30, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(120)])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('completed', 'completed')], default='Pending', max_length=50)),
                ('packageID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='photo_app.photopackage')),
                ('sessions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='session_app.sessioncon')),
            ],
        ),
    ]
